In [1]:
import numpy as np

In [291]:
#1. Create a null array of size 10 but the fifth value which is 1
a = np.ones(10)
a[:4]=np.nan
a[5:]=np.nan
a

array([nan, nan, nan, nan,  1., nan, nan, nan, nan, nan])

In [84]:
#2. Reverse a above created array (first element becomes last)
b = a[-1::-1]
b


array([nan, nan, nan, nan, nan,  1., nan, nan, nan, nan])

In [85]:
#3. Create a 3x3 matrix with values ranging from 0 to 8
grid = np.arange(9).reshape(1,3,3)
grid

array([[[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]]])

In [170]:
#4. Find indices of non-zero elements from [1,2,0,0,4,0]
test = np.array([1,2,0,0,4,0], np.int64)
zeroSpots = np.where(test != 0)
zeroSpots

(array([0, 1, 4], dtype=int64),)

In [176]:
#5. Create a 3x3x3 array with random values
x = np.random.randint(1,100,(3,3,3))
x

array([[[72, 71, 50],
        [59, 13, 70],
        [ 2, 84, 80]],

       [[12, 66, 44],
        [15, 28, 34],
        [77, 61, 49]],

       [[31, 42, 77],
        [17, 34, 29],
        [71, 81, 24]]])

In [177]:
#6. Create a 10x10 array with random values and find the minimum and maximum values
x = np.random.randint(1,100,(10,10))
print(x)
print("Smallest element is {}".format(x.min()))
print("Largest element is {}".format(x.max()))

[[95 32 57 75 11 87 87 31 99  6]
 [26 10 60 27 60 58 73 39 57 42]
 [88  4 47 96 37 58 20  5 95 37]
 [58 14 60 78 12 91 41 20 45 65]
 [92 50 20 60 41 33 38 56 73  1]
 [46 92 75 98  6 15 99 87 89  1]
 [71 36 78 30 54 56 64 16 96 75]
 [15 60 71 82 69 62 86 97 37 39]
 [86 81 50 93 98 72 81 96  7 50]
 [90 50 95 46  2 90 18 52 82 47]]
Smallest element is 1
Largest element is 99


In [178]:
#7. Create a random vector of size 30 and find the mean value
x = np.random.randint(1,10,(1,30))
x.mean()

4.733333333333333

In [156]:
#8. Create a 2d array with 1 on the border and 0 inside
a = np.ones((5,5), dtype=np.int64)
a[1:-1,1:-1] = 0
a

array([[1, 1, 1, 1, 1],
       [1, 0, 0, 0, 1],
       [1, 0, 0, 0, 1],
       [1, 0, 0, 0, 1],
       [1, 1, 1, 1, 1]], dtype=int64)

In [142]:
#9. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product)

A = np.random.randint(1,100,(5,3)).astype(np.int64)
B = np.random.randint(1,100,(3,2)).astype(np.int64)

np.matmul(A,B)


array([[14536,  5043],
       [14635,  5529],
       [ 8320,  2954],
       [17915,  5881],
       [16928,  5068]], dtype=int64)

In [143]:
#10. Extract the integer part of a random array

x = 10*np.random.random_sample((1, 10))
print(x)

y = x[::].astype(np.int64)
print(y)


[[3.4046992  9.31978835 8.28924483 1.52792101 0.88451781 9.09321514
  8.26197573 6.75677791 1.18292874 8.02450976]]
[[3 9 8 1 0 9 8 6 1 8]]


In [132]:
#11. Create a 5x5 matrix with row values ranging from 0 to 4

4 * np.random.random_sample((5, 5))

array([[0.6932049 , 0.5840123 , 2.10053345, 3.07002219, 3.79828724],
       [1.55719022, 0.99619558, 1.04407565, 1.42531075, 3.33020452],
       [0.05333308, 0.69291821, 3.41523662, 3.44140873, 2.92293524],
       [3.37134853, 3.5327757 , 0.70034414, 2.46284715, 2.82720311],
       [1.38472499, 3.6562084 , 1.8580339 , 2.2329077 , 2.55928361]])

In [146]:
#12.  Create a random vector of size 10 and sort it

A = np.random.random_sample((1, 10))
print(A)

B=np.sort(A)
print(B)


[[0.92809939 0.6097125  0.69382766 0.55421622 0.87151592 0.25994439
  0.78302314 0.79242124 0.12628347 0.80733769]]
[[0.12628347 0.25994439 0.55421622 0.6097125  0.69382766 0.78302314
  0.79242124 0.80733769 0.87151592 0.92809939]]


In [4]:
#13. Consider two random array A anb B, check if they are equal.

A = np.array([1,2,3,4,5,6], np.int64)
B = np.array([1,2,3,4,5,6], np.int64)

if A.size != B.size:
    print("Cannot compare. Dimensions are different")
else:
    AreEqual = True
    for i in range(0,A.size):
        if A[i] != B[i]:
            AreEqual = False
            exit
    print("These arrays are equal : {}".format(AreEqual))  

np.array_equal(A,B)


These arrays are equal : True


True

In [300]:
#14. How to tell if a given 2D array has null columns?

A = np.array((
    [2, 3, 5, 4, np.nan, 1], 
    [4, 3, 1, 2, np.nan, 5], 
    [5, 3, 1, 2, np.nan, 4], 
    [1, 4, 3, 5, np.nan, 2]), float)

B = np.array((
    [2, 3, 5, 4, 0, 1], 
    [4, 3, 1, 2, 0, 5], 
    [5, 3, 1, 2, 0, 4], 
    [1, 4, 3, 5, 0, 2]), float)

# Function to determine if 2D arra has null columns
def HasEmptyColumn(x):
    HasNanCol = False

    for i in np.sum(x, axis=0):
        if np.isnan(i):
            HasNanCol = True
    return HasNanCol   

print("A has an empty column?: {}".format(HasEmptyColumn(A)))
print("B has an empty column?: {}".format(HasEmptyColumn(B)))



A has an empty column?: True
B has an empty column?: False


In [306]:
#15. Considering a four dimensions array, how to get sum over the last two axis at once?

A = np.random.randint(1,100,(3,3,3,3))
sumOverLastTwo = np.sum(A, axis=(2,3))
sumOverLastTwo

array([[536, 360, 408],
       [405, 400, 401],
       [484, 315, 365]])

In [307]:
#16. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)?
A = np.random.randint(1,100,(5,5,3))
B = np.random.randint(1,100,(5,5))

#NOTE: order matters, operation is not commutative
np.matmul(B,A)

array([[[ 8047,  6577, 10071],
        [ 8999,  9899, 11205],
        [ 8483,  9435,  9589],
        [ 9751, 11425, 12809],
        [15234, 14531, 17236]],

       [[15635, 19265, 14012],
        [ 6326, 14032,  7380],
        [13068, 19046, 10212],
        [11330, 20989, 12083],
        [19538, 27637, 16002]],

       [[18020, 15848, 13418],
        [ 8814,  8491, 12231],
        [15258, 15701, 12005],
        [15136, 13684, 15406],
        [22379, 22714, 20265]],

       [[ 9953, 12076, 18951],
        [ 5872, 14293, 10704],
        [ 7782, 12051, 16042],
        [ 6520, 15391, 14557],
        [14859, 22087, 26901]],

       [[ 7417, 15935, 11164],
        [ 1776, 12206,  3929],
        [ 7110, 13468, 10111],
        [ 6444, 14616,  9315],
        [ 7364, 24110, 12612]]])

In [5]:
#17. Extract all the contiguous 3x3 blocks from a random 10x10 matrix

x = np.random.randint(1,100,(5,5))
print(x)

for i in range(0, 5-3+1, 1):
        for j in range(0, 5-3+1, 1):
            result = x[i:i+3,j:j+3]
            print(result)

[[13 67 60 36 32]
 [ 6 33  2 55 37]
 [ 1 36 52 83 80]
 [44 59 33 36 45]
 [83 75 31 72 53]]
[[13 67 60]
 [ 6 33  2]
 [ 1 36 52]]
[[67 60 36]
 [33  2 55]
 [36 52 83]]
[[60 36 32]
 [ 2 55 37]
 [52 83 80]]
[[ 6 33  2]
 [ 1 36 52]
 [44 59 33]]
[[33  2 55]
 [36 52 83]
 [59 33 36]]
[[ 2 55 37]
 [52 83 80]
 [33 36 45]]
[[ 1 36 52]
 [44 59 33]
 [83 75 31]]
[[36 52 83]
 [59 33 36]
 [75 31 72]]
[[52 83 80]
 [33 36 45]
 [31 72 53]]


In [190]:
np.arange(0, 16, 4) 

array([ 0,  4,  8, 12])

In [309]:
#18. Consider a 16x16 array, how to get the block-sum (block size is 4x4)?

x = np.ones((16,16))

blocksize = 4

# result = np.add.reduceat(
#           np.add.reduceat(x, 
#               np.arange(0, x.shape[0], blocksize), axis=0),  ==> np.arange(0, 16, 4) = 0, 4, 8, 12 
#               np.arange(0, x.shape[1], blocksize), axis=1)   ==> np.arange(0, 16, 4) = 0, 4, 8, 12 
#
result = np.add.reduceat(np.add.reduceat(x, np.arange(0, x.shape[0], blocksize), axis=0), np.arange(0, x.shape[1], blocksize), axis=1)
print(result)

[[16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]]


In [214]:
#19. Generate 2 random gaussian distributions and run a t-test to see differences
import scipy.stats as stats


a = np.random.normal(0, 1, size=100)
b = np.random.normal(.50, 1, size=100)

stats.ttest_ind(a, b)   


Ttest_indResult(statistic=-3.4056546727422394, pvalue=0.0007991560628827487)